use std::fmt::Write;
use std::fs;

use camino::Utf8Path;

use crate::report::Diagnostic;

/// Produce a best-guess source-form elu.toml for the project tree at `root`.
/// The output always parses and validates; non-inferrable fields are filled
/// with TODO comments/values so the author sees what to edit.
pub fn infer_from_dir(root: &Utf8Path) -> Result<String, Diagnostic> {
    let cargo = read_text(root, "Cargo.toml");
    let pkg_json = read_text(root, "package.json");
    let pyproject = read_text(root, "pyproject.toml");
    let go_mod = read_text(root, "go.mod");
    let makefile = read_text(root, "Makefile");
    let has_readme = root.join("README.md").as_std_path().exists();
    let has_changelog = root.join("CHANGELOG.md").as_std_path().exists();

    let (name, version, bin_layer) = if let Some(ref t) = cargo {
        let n = toml_get_str(t, "package.name").unwrap_or_else(|| "todo-name".to_string());
        let v = toml_get_str(t, "package.version").unwrap_or_else(|| "0.1.0".to_string());
        let layer = format!(
            "[[layer]]\nname    = \"bin\"\n# Inferred from Cargo.toml. Run `cargo build --release` first.\ninclude = [\"target/release/{n}\"]\nstrip   = \"target/release/\"\nplace   = \"bin/\"\n\n"
        );
        (n, v, Some(layer))
    } else if let Some(ref t) = pkg_json {
        let n = last_segment(&json_get_str(t, "name").unwrap_or_else(|| "todo-name".to_string()));
        let v = json_get_str(t, "version").unwrap_or_else(|| "0.1.0".to_string());
        let layer = "[[layer]]\nname    = \"lib\"\n# Inferred from package.json. Run your bundler first.\ninclude = [\"dist/**\"]\n\n".to_string();
        (n, v, Some(layer))
    } else if let Some(ref t) = pyproject {
        let n = toml_get_str(t, "project.name")
            .or_else(|| toml_get_str(t, "tool.poetry.name"))
            .unwrap_or_else(|| "todo-name".to_string());
        let v = toml_get_str(t, "project.version")
            .or_else(|| toml_get_str(t, "tool.poetry.version"))
            .unwrap_or_else(|| "0.1.0".to_string());
        let layer = "[[layer]]\nname    = \"wheel\"\n# Inferred from pyproject.toml. Run `python -m build` first.\ninclude = [\"dist/*.whl\"]\n\n".to_string();
        (n, v, Some(layer))
    } else if let Some(ref t) = go_mod {
        let module = t
            .lines()
            .find_map(|l| l.strip_prefix("module "))
            .map(str::trim)
            .unwrap_or("todo-name");
        let n = last_segment(module);
        let layer = format!(
            "[[layer]]\nname    = \"bin\"\n# Inferred from go.mod. Run `go build -o bin/{n}` first.\ninclude = [\"bin/{n}\"]\n\n"
        );
        (n, "0.1.0".to_string(), Some(layer))
    } else if makefile.is_some() {
        let layer = "[[layer]]\nname    = \"bin\"\n# TODO: Inferred from Makefile. Set include to your build output.\ninclude = [\"bin/TODO\"]\n\n".to_string();
        ("todo-name".to_string(), "0.1.0".to_string(), Some(layer))
    } else {
        ("todo-name".to_string(), "0.1.0".to_string(), None)
    };

    let docs_layer = if has_readme || has_changelog {
        let mut inc = Vec::new();
        if has_readme {
            inc.push("\"README.md\"");
        }
        if has_changelog {
            inc.push("\"CHANGELOG.md\"");
        }
        Some(format!(
            "[[layer]]\nname    = \"docs\"\ninclude = [{}]\nplace   = \"share/doc/{name}/\"\n\n",
            inc.join(", ")
        ))
    } else {
        None
    };

    let mut out = String::new();
    writeln!(out, "# Generated by `elu init --from`. Review and edit before running `elu build`.").ok();
    writeln!(out).ok();
    writeln!(out, "schema = 1").ok();
    writeln!(out).ok();
    writeln!(out, "[package]").ok();
    writeln!(out, "namespace   = \"todo-namespace\"  # TODO: set your namespace").ok();
    writeln!(out, "name        = \"{name}\"").ok();
    writeln!(out, "version     = \"{version}\"").ok();
    writeln!(out, "kind        = \"native\"  # TODO: change to ox-skill/ox-persona/ox-runtime if appropriate").ok();
    writeln!(out, "description = \"TODO: one-line description\"").ok();
    writeln!(out).ok();
    if let Some(b) = bin_layer {
        out.push_str(&b);
    }
    if let Some(d) = docs_layer {
        out.push_str(&d);
    }

    Ok(out)
}

fn read_text(root: &Utf8Path, name: &str) -> Option<String> {
    fs::read_to_string(root.join(name).as_std_path()).ok()
}

fn toml_get_str(src: &str, dotted: &str) -> Option<String> {
    let v: toml::Value = src.parse().ok()?;
    let mut cur = &v;
    for seg in dotted.split('.') {
        cur = cur.get(seg)?;
    }
    cur.as_str().map(str::to_string)
}

fn json_get_str(src: &str, key: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(src).ok()?;
    v.get(key)?.as_str().map(str::to_string)
}

fn last_segment(s: &str) -> String {
    s.trim_start_matches('@')
        .rsplit(['/', '.'])
        .next()
        .unwrap_or(s)
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn last_segment_strips_scope_and_domain() {
        assert_eq!(last_segment("@scope/pkg"), "pkg");
        assert_eq!(last_segment("github.com/user/repo"), "repo");
        assert_eq!(last_segment("plain"), "plain");
    }
}
